### PR TITLE
add known command names for Assignment recognition

### PR DESCRIPTION
**Pull request by nittka**
Some assignments were not recognized as such because their name was in the list of SpecialCommandName of OtherName. Adding them as possible names will even satisfy the added expected assignments in Integration.java. The remaining failing Integration tests will be much harder to fix.

### CODE REVIEW

**Comment by nittka** [comment]
I even think that some of the special command names can be eliminated now. With the modified grammar, more assignments than before are recognized. SpecialCommandNames should only have to contain those entries that are also used elsewhere in the grammar as keywords. Given some time, I will try reduce the list.

**Comment by thSoft** [comment]
Yes, I already removed the names of music functions in 2c3ee2c.

**Comment by nittka** [comment]
I will fix the SpecialCommand/Othername issue, just wanted to let you know that commit:196a4b9715336a5b2b95a0eea779319644c58079 (partially?) fixes #79.

**Comment by thSoft** [comment]
Thanks for increasing the test coverage and number of passes!

**Pull request merged**
