### PR TITLE
Migrate to Xtext 2.10

### PR DESCRIPTION
**Pull request by nittka**
This PR is based on the Xtext210 branch you tried out for #85. I added one further commit integrating the commits on master since the original branch was created.

The maven build does not work yet. I suggest to first move to Xtext 2.10 on master using this PR (keeping the current master as "Xtext 2.7 end of life" branch so we can easily check regression issues), adapt the Oomph setup to include a master and a xtext27 stream and get the Tycho build working.

Migration to Xtext 2.13 will be easier (less merge conflicts) as the project layout has not changed.

... Is it possible just to rename master and make this branch the new master?

### CODE REVIEW

**Comment by thSoft** [comment]
Thanks! Now there are two Elysium.setup files. I think org.elysium.parent/Elysium.setup should be moved to the root, overwriting the old one. This way we can keep the setup URL. What do you think?

**Comment by nittka** [comment]
Probably we should - for consistency (I put it into the parent, because having it in the workspace is usually nicer).

Will you open a 2.7 branch from before the merge? I'd like to have that. The advantage of having that branch would be, that we could add a stream to the Oomph setup which sets up a working eclipse for investigating regression issues.

I have played around with the maven build yesterday and would open a PR with changes necessary to get it running. One small issue is a test that creates an actual file for testing an include (encoding problem file vs. code) which does not arise when running the test in Eclipse. A bigger one is that the tests need a LilyPond installation (for includes) whose path I was not able to pass dynamically to the maven build. And one I'd let you handle is the packaging of the licence (build of branding feature).

**Comment by thSoft** [comment]
I moved the setup and created an xtext27 maintenance branch.

**Comment by thSoft** [comment]
I did further tweaks in the setup. You might have to clear `~/.eclipse/org.eclipse.oomph.setup/cache` for the renaming of the setup to take effect.

**Pull request merged**
