### PR TITLE
code completion for midi instruments

### PR DESCRIPTION
**Pull request by nittka**
This is a very simple code completion for the midi instruments listed at http://lilypond.org/doc/v2.19/Documentation/notation/midi-instruments

It fires within the quotation marks in an assignment like `\set midiInstrument =#"violin"`

### CODE REVIEW

**Comment by nittka** [comment]
The modifications in the Oomph setup were necessary for running the plugin test within Eclipse. I hope the additional dependencies will work for target platforms other than Mars as well...

**Comment by thSoft** [comment]
Thanks for the feature and the tests! What was the error exactly when running the UI tests? I managed to run them successfully with Oxygen using [this launch config](https://github.com/thSoft/elysium/blob/master/org.elysium.parent/org.elysium.ui.tests/Elysium%20UI%20Tests.launch).

**Comment by nittka** [comment]
Currently, I use a Mars target platform created by Oomph. Without org.eclipse.pde.junit.runtime the launch would not start at all 

> Required plug-in 'org.eclipse.pde.junit.runtime' could not be found.

With pde.junit there was an AbstractMethodError exception

> Caused by: java.lang.AbstractMethodError: org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests...

Adding jde.junit4 got rid of that. Possibly, the Oxygen target platform does not need these explicit requirements. If they do not hurt, I'd like to keep them in the setup.

**Comment by thSoft** [comment]
Strange, it looks like [this issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=216946) which is said to be fixed before Mars. It does not hurt much, but on the long run, we should consider dropping supporting target platforms of older versions.

**Pull request merged**
