### PR TITLE
#197 Upgrade dependencies

### LINKED ISSUE #197: Update target platform to work with Big Sur
On macOS 11 Big Sur, starting the Elysium launch configuration fails with:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=54117, tid=775
#
# JRE version: OpenJDK Runtime Environment (11.0.2+9) (build 11.0.2+9)
# Java VM: OpenJDK 64-Bit Server VM (11.0.2+9, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  0x0000000000000000
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/thsoft/Development/elysium/Eclipse.app/Contents/MacOS/hs_err_pid54117.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
The launch configuration command line is:
```
/Users/thsoft/.sdkman/candidates/java/11.0.2-open/bin/java
-XstartOnFirstThread
-Xmx1024m
-XX:MaxPermSize=256m
-Dorg.eclipse.swt.internal.carbon.smallFonts
-Dorg.osgi.framework.bundle.parent=ext
-Declipse.pde.launch=true
--add-modules=ALL-SYSTEM
-Dfile.encoding=UTF-8
-classpath /Users/thsoft/.p2/pool/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar org.eclipse.equinox.launcher.Main
-launcher /Users/thsoft/Development/elysium/ws/.metadata/.plugins/org.eclipse.pde.core/.install_folders/1609691687860/Eclipse.app/Contents/MacOS/eclipse
-name Eclipse
-showsplash 600
-product org.eclipse.platform.ide
-data /Users/thsoft/Development/elysium/ws/.runtime/Elysium
-configuration file:/Users/thsoft/Development/elysium/ws/.metadata/.plugins/org.eclipse.pde.core/Elysium/
-dev file:/Users/thsoft/Development/elysium/ws/.metadata/.plugins/org.eclipse.pde.core/Elysium/dev.properties
-os macosx
-ws cocoa
-arch x86_64
-nl hu_HU
-consoleLog
```
`/Users/thsoft/.p2/pool/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar` is of a suspiciously old version, so updating the target platform might solve the problem.

### PR DESCRIPTION
**Pull request by thSoft**
Fixes #197.

### CODE REVIEW

**Comment by thSoft** [comment]
Unfortunately there is a regression in the integration tests. Could you please investigate it, @nittka?

**Comment by nittka** [comment]
Yes, I'll have a look. I just checked that the tests still run successfully in my old Eclipse development environment. I'll first have to setup an updated Eclipse using the setup from the branch to check what might be the problem with the latest Xtext.

**Comment by thSoft** [comment]
Great, thanks! Use version 2020-12 for both Eclipse application and target platform during setup (I'll update the Contributor Guide wiki page when this PR is merged to master).

**Comment by nittka** [comment]
I guess, investigating this problem might take a bit. While the variable is marked as unknown when running the unit test, it can be resolved in a runtime workspace (at least there are no errors and F3 finds a definition). I am not aware that we modified in the actual linking in the UI-Module.

Was removing the caching of default imports for tests necessary? The execution time for the integration tests is much higher than in the "old" verison.

**Comment by thSoft** [comment]
> Was removing the caching of default imports for tests necessary? The execution time for the integration tests is much higher than in the "old" verison.

No, thanks for pointing this out. It was just because the Xtext testing API changed significantly and I was lazy to migrate the manual injection code. :) I'd gladly migrate it, but unfortunately I couldn't find any migration guide. Do you have any pointer?

**Comment by nittka** [comment]
OK, the problem is almost certainly caused by the simplifying changes in the Integration test itself. Now the parsehelper only gets the file content but not the URI (previously the file URI was explicitly set), so a synthetic URI is created. But this URI cannot be used to resolve an included file (no base URI for resolution). For default includes this is irrelevant because they are absolute...
This also explains why the test fails while there are no errors in the runtime workspace.

The problem can be reproduced by a trivial test case (ily defines a variable, ly includes and references the variable). I will try to update the tests and also reintroduce the cache if possible. I don't know of a migration guide and have not intensively worked with Xtext quite some time.

**Comment by nittka** [comment]
I did not want to modify this branch directly, so I created a PR for adding a fixing commit to it.
Thanks for the effort of updating. Currently, we use no new Xtext features, so requiring Xtext 2.24 could by quite restricting. But I guess whoever is using Elysium is not really bound to an old version...

**Comment by thSoft** [comment]
> OK, the problem is almost certainly caused by the simplifying changes in the Integration test itself.

Sorry for breaking the test. :( Thank you for fixing regression caused by me!

> Currently, we use no new Xtext features, so requiring Xtext 2.24 could by quite restricting.

I know, I just wanted to upgrade the dependencies for good since they were quite old.

**Review by nittka — APPROVED** [review]

**Pull request merged**
